-- Create tables
CREATE TABLE IF NOT EXISTS client_intakes (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text,
  phone text,
  age integer,
  gender text,
  current_weight real,
  fitness_goal text,
  medical_conditions text,
  status text default 'pending',
  payment_status text default 'unpaid',
  amount_paid numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE IF NOT EXISTS contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text,
  message text not null,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE IF NOT EXISTS bookings (
  id bigint generated by default as identity primary key,
  client_name text not null,
  client_email text,
  client_phone text,
  goal text,
  booking_date text,
  booking_time text,
  status text default 'pending',
  payment_status text default 'unpaid',
  amount_paid numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE IF NOT EXISTS site_visits (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (Optional, but good practice. We'll set public access policies for anon)
ALTER TABLE client_intakes ENABLE ROW LEVEL SECURITY;
ALTER TABLE contact_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_visits ENABLE ROW LEVEL SECURITY;

-- Allow anon public inserts
CREATE POLICY "Enable public anon insert for client_intakes" ON client_intakes FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Enable public anon insert for contact_messages" ON contact_messages FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Enable public anon insert for bookings" ON bookings FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Enable public anon insert for site_visits" ON site_visits FOR INSERT TO public WITH CHECK (true);

-- Allow reading all (for your Admin Dashboard)
CREATE POLICY "Enable read access for all" ON client_intakes FOR SELECT USING (true);
CREATE POLICY "Enable read access for all" ON contact_messages FOR SELECT USING (true);
CREATE POLICY "Enable read access for all" ON bookings FOR SELECT USING (true);
CREATE POLICY "Enable read access for all" ON site_visits FOR SELECT USING (true);
CREATE POLICY "Enable update access for all" ON client_intakes FOR UPDATE USING (true);
CREATE POLICY "Enable update access for all" ON contact_messages FOR UPDATE USING (true);
CREATE POLICY "Enable update access for all" ON bookings FOR UPDATE USING (true);

-- ==========================================
-- STORAGE BUCKET CONFIGURATION
-- ==========================================

-- Insert the bucket explicitly
INSERT INTO storage.buckets (id, name, public) 
VALUES ('client-intakes', 'client-intakes', true)
ON CONFLICT (id) DO NOTHING;

-- Grant public upload access (INSERT)
CREATE POLICY "Allow public uploads to client-intakes" 
ON storage.objects FOR INSERT TO public 
WITH CHECK ( bucket_id = 'client-intakes' );

-- Grant public read access (SELECT)
CREATE POLICY "Allow public read access to client-intakes" 
ON storage.objects FOR SELECT TO public 
USING ( bucket_id = 'client-intakes' );
